name: kmeans

model:
    filepath: src/kmeans.py
    class: KMeansAspectDetector
    parameters:
        k: 7
        
        
embedding:
    w2v:
        lim: 10000
    

sentences:
    sentence1:  aised in Scranton, Pennsylvania, and New Castle County, 
                Delaware, Biden studied at the University of Delaware before earning his law degree from Syracuse University in 1968. 
                He was elected to the New Castle County Council in 1970 and became the sixth-youngest senator in American history 
                when he was elected to the U.S. Senate from Delaware in 1972, at the age of 29. Biden was a longtime member of the 
                Senate Foreign Relations Committee and eventually became its chairman. He also chaired the Senate Judiciary Committee 
                from 1987 to 1995, dealing with drug policy, crime prevention, and civil liberties issues; led the effort to pass the 
                Violent Crime Control and Law Enforcement Act and the Violence Against Women Act; and oversaw six U.S. Supreme Court 
                confirmation hearings, including the contentious hearings for Robert Bork and Clarence Thomas. 
                He ran unsuccessfully for the Democratic presidential nomination in 1988 and again in 2008.
    sentence2:  Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics. The character was 
                co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and 
                Jack Kirby. The character made his first appearance in Tales of Suspense 39 (cover dated March 1963), and received 
                his own title in Iron Man 1 (May 1968). Also in 1963, the character founded the Avengers alongside Thor, Ant-Man, 
                Wasp and the Hulk.

